name: Deploy

on:
  push:
    branches: ["master"]

    workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish .NET
        uses: dotnet publish Imc.csproj -c:Release -o docs --nologo

      - name: Setup .NET
        uses: actions/configure-dotnet@v3      
        with:
          dotnet-version: '9.0.x'

      - name: Install dependencies
        run: dotnet workload install wasm-tools

      - name: Build
        run: dotnet build -c Releaase --no-restore

      - name: Setup pages
        uses: actions/configure-pages@v4
        
      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.docs/wwwroot'
      
      -name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4   
      